DROP DATABASE IF EXISTS RateMyCourse;

create DATABASE IF NOT EXISTS RateMyCourse;
USE RateMyCourse;

CREATE TABLE if NOT EXISTS COURSE(

  COURSE_ID CHAR(10) NOT NULL PRIMARY KEY,
  COURSE_NAME VARCHAR(50) NOT NULL,
  COURSE_COLLEGE VARCHAR(50),
  COURSE_DESCRIPTION VARCHAR(2000)

  );


CREATE TABLE if NOT EXISTS PREREQUISITE(

  PREREQUISITE_ID CHAR(10) NOT NULL,
  COURSE_ID CHAR(10) NOT NULL REFERENCES COURSE(COURSE_ID)

  );
CREATE TABLE if NOT EXISTS USERS(

  USERNAME VARCHAR(30) NOT NULL PRIMARY KEY ,
  USER_PASSWORD VARCHAR(20) NOT NULL,
  FIRST_NAME VARCHAR(30) NOT NULL,
  LAST_NAME VARCHAR(30) NOT NULL,
  PRIVILEGE_LEVEL SMALLINT NOT NULL

  );

CREATE TABLE if NOT EXISTS COMMENT(

  COMMENT_ID DECIMAL(10) NOT NULL PRIMARY KEY,
  COMMENT_CATEGORY DECIMAL(1) NOT NULL,
  USERNAME VARCHAR(30) NOT NULL REFERENCES USERS(USER_ID),
  COMMENT_BODY VARCHAR(10000) NOT NULL,
  COMMENT_DATE DATE NOT NULL,
  COMMENT_RATING DECIMAL(1) NULL,
  COURSE_ID CHAR(10) NOT NULL REFERENCES COURSE(COURSE_ID)

  );


CREATE TABLE if NOT EXISTS COURSE_RATINGS(

  RATING_ID DECIMAL(10) NOT NULL PRIMARY KEY,
  LEVEL_OF_DIFFICULTY DECIMAL (1) NOT NULL,
  RECOMMENDED DECIMAL(1),
  COURSE_ID CHAR(10) NOT NULL REFERENCES COURSE(COURSE_ID),
  USERNAME VARCHAR(30) NOT NULL REFERENCES USERS(USER_ID)

);


CREATE TABLE if NOT EXISTS REPORTS(

  REPORT_ID DECIMAL(10) NOT NULL PRIMARY KEY,
  REPORTER_FIRSTNAME VARCHAR(30) NOT NULL,
  REPORTER_LASTNAME VARCHAR(30) NOT NULL,
  EMAIL VARCHAR(30) NOT NULL ,
  REPORT_DATE DATE NOT NULL,
  REPORT_MESSAGE VARCHAR(10000) NOT NULL,
  REPORTED_COMMENT_ID DECIMAL(10) NOT NULL REFERENCES COMMENT (COMMENT_ID)

  );


INSERT INTO USERS VALUES('admin', 'pass' , 'Nadia', 'Hasan', 1);
INSERT INTO USERS VALUES('user1', '1234' , 'Harold', 'Welch', 2);
INSERT INTO USERS VALUES('user2', '1234' , 'Thomas', 'Johnson', 2);
INSERT INTO USERS VALUES('user3', '1234' , 'James', 'Allmon', 2);
INSERT INTO USERS VALUES('user4', '1234' , 'Ann', 'Rochester', 2);

INSERT INTO COURSE VALUES('CEN4010', 'Software Engineering', 'IT', 'Software life cycle' );
INSERT INTO COURSE VALUES('CNT3004', 'Computer Networks', 'IT', 'Introduction to computer networks' );
INSERT INTO COURSE VALUES('COP4610', 'Operating Systems', 'IT', 'Concepts of operating systems' );
INSERT INTO COURSE VALUES('COP3530', 'Data Structures', 'IT', 'Introduction to algorithms and data structures' );
INSERT INTO COURSE VALUES('COP3834', 'Web App Development', 'IT', 'Introduction to web app development' );


use RateMyCourse;
select * from COURSE where COURSE_NAME like "%ware%" or COURSE_ID like "%COP%";
